# Generated by Django 3.2.9 on 2022-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_song_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
