# Generated by Django 3.2.9 on 2022-06-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_song_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
    ]
