# Generated by Django 4.0.5 on 2022-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_author_featured_image_song_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
