# Generated by Django 4.0.5 on 2022-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_alter_song_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
