# Generated by Django 4.0.5 on 2022-06-06 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0010_alter_song_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist_song',
            new_name='PlaylistSong',
        ),
    ]
